// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oqlmapper.actions;

import oqlmapper.implementation.QueryExecution;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * All templates are loaded in memory to be executed directly. 
 */
public class ExecuteOQLQuery extends CustomJavaAction<Boolean>
{
	private String TemplateName;
	private IMendixObject ParentObject;
	private String OptionalOQLQuery;

	public ExecuteOQLQuery(IContext context, String TemplateName, IMendixObject ParentObject, String OptionalOQLQuery)
	{
		super(context);
		this.TemplateName = TemplateName;
		this.ParentObject = ParentObject;
		this.OptionalOQLQuery = OptionalOQLQuery;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		QueryExecution execution = new QueryExecution(TemplateName, OptionalOQLQuery, ParentObject);
		return execution.executeQuery(getContext());		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ExecuteOQLQuery";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
