// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oqlmapper.actions;

import oqlmapper.implementation.Mapping;
import oqlmapper.implementation.QueryExecution;
import oqlmapper.implementation.Template;
import oqlmapper.proxies.OQLMapping;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class LoadInMemory extends CustomJavaAction<Boolean>
{
	private IMendixObject __QueryTemplate;
	private oqlmapper.proxies.OQLTemplate QueryTemplate;
	private java.util.List<IMendixObject> __MappingList;
	private java.util.List<oqlmapper.proxies.OQLMapping> MappingList;

	public LoadInMemory(IContext context, IMendixObject QueryTemplate, java.util.List<IMendixObject> MappingList)
	{
		super(context);
		this.__QueryTemplate = QueryTemplate;
		this.__MappingList = MappingList;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.QueryTemplate = __QueryTemplate == null ? null : oqlmapper.proxies.OQLTemplate.initialize(getContext(), __QueryTemplate);

		this.MappingList = new java.util.ArrayList<oqlmapper.proxies.OQLMapping>();
		if (__MappingList != null)
			for (IMendixObject __MappingListElement : __MappingList)
				this.MappingList.add(oqlmapper.proxies.OQLMapping.initialize(getContext(), __MappingListElement));

		// BEGIN USER CODE
		Template template = new Template(this.QueryTemplate.getOQLStatement(), 
				this.QueryTemplate.getOQLTemplate_ParentObjectType().getCompleteName(), 
				this.QueryTemplate.getOQLTemplate_MxObjectReference().getCompleteName(), 
				this.QueryTemplate.getOQLTemplate_RowObjectType().getCompleteName(),
				this.QueryTemplate.getContextObjectDescription());		
		for(OQLMapping map : this.MappingList)
		{
			template.addMapping(new Mapping(map.getAliasName(), map.getOQLMapping_MxObjectMember().getAttributeName(), map.getParserType()));
		}
		QueryExecution.addTemplate(this.QueryTemplate.getName(), template);
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "LoadInMemory";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
